/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fb.gui;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        dpContenedor = new javax.swing.JDesktopPane();
        mbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        miAutor = new javax.swing.JMenuItem();
        miLibro = new javax.swing.JMenuItem();
        miPunto = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miColaborador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miRegistroPedido = new javax.swing.JMenuItem();
        miSeguimientoPedido = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpContenedorLayout = new javax.swing.GroupLayout(dpContenedor);
        dpContenedor.setLayout(dpContenedorLayout);
        dpContenedorLayout.setHorizontalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpContenedorLayout.setVerticalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");
        mbMenu.add(jMenu1);

        jMenu2.setText("Mantenimiento");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        miAutor.setText("Autor");
        miAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAutorActionPerformed(evt);
            }
        });
        jMenu2.add(miAutor);

        miLibro.setText("Libro");
        miLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLibroActionPerformed(evt);
            }
        });
        jMenu2.add(miLibro);

        miPunto.setText("Punto de entrega");
        miPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPuntoActionPerformed(evt);
            }
        });
        jMenu2.add(miPunto);

        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miCliente);
        jMenu2.add(jSeparator1);

        miColaborador.setText("Colaborador");
        miColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miColaboradorActionPerformed(evt);
            }
        });
        jMenu2.add(miColaborador);

        mbMenu.add(jMenu2);

        jMenu4.setText("Ventas");

        miRegistroPedido.setText("Registro de Pedido");
        miRegistroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroPedidoActionPerformed(evt);
            }
        });
        jMenu4.add(miRegistroPedido);

        miSeguimientoPedido.setText("Seguimiento de Pedido");
        jMenu4.add(miSeguimientoPedido);

        mbMenu.add(jMenu4);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miColaboradorActionPerformed
        try {            
            MantenimientoColaborador man = new MantenimientoColaborador();
            dpContenedor.add(man);
            man.setVisible(true);
            man.setMaximum(false);
            man.setLocation((dpContenedor.getSize().width - man.getSize().width)/2, (dpContenedor.getSize().height - man.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miColaboradorActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        try {            
            MantenimientoCliente man = new MantenimientoCliente();
            dpContenedor.add(man);
            man.setVisible(true);
            man.setMaximum(false);
            man.setLocation((dpContenedor.getSize().width - man.getSize().width)/2, (dpContenedor.getSize().height - man.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miClienteActionPerformed

    private void miRegistroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroPedidoActionPerformed
         try {            
            RegistroPedido rp = new RegistroPedido();
            dpContenedor.add(rp);
            rp.setVisible(true);
            rp.setMaximum(false);            
            rp.setLocation((dpContenedor.getSize().width - rp.getSize().width)/2, (dpContenedor.getSize().height - rp.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miRegistroPedidoActionPerformed

    private void miAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAutorActionPerformed
        try {            
            MantenimientoAutor aut = new MantenimientoAutor();
            dpContenedor.add(aut);
            aut.setVisible(true);
            aut.setMaximum(false);
            aut.setLocation((dpContenedor.getSize().width - aut.getSize().width)/2, (dpContenedor.getSize().height - aut.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miAutorActionPerformed

    private void miLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLibroActionPerformed
        try {            
            MantenimientoLibro lib = new MantenimientoLibro();
            dpContenedor.add(lib);
            lib.setVisible(true);
            lib.setMaximum(false);
            lib.setLocation((dpContenedor.getSize().width - lib.getSize().width)/2, (dpContenedor.getSize().height - lib.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miLibroActionPerformed

    private void miPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPuntoActionPerformed
        try {            
            MantenimientoPunto lib = new MantenimientoPunto();
            dpContenedor.add(lib);
            lib.setVisible(true);
            lib.setMaximum(false);
            lib.setLocation((dpContenedor.getSize().width - lib.getSize().width)/2, (dpContenedor.getSize().height - lib.getSize().height)/2);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miPuntoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpContenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAutor;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miColaborador;
    private javax.swing.JMenuItem miLibro;
    private javax.swing.JMenuItem miPunto;
    private javax.swing.JMenuItem miRegistroPedido;
    private javax.swing.JMenuItem miSeguimientoPedido;
    // End of variables declaration//GEN-END:variables
}
