/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package fb.gui;

import fb.dto.PedidoDetalleDTO;
import fb.model.Libro;
import fb.util.MultiHelper;
import java.awt.Image;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author USUARIO
 */
public class RegistroPedido extends javax.swing.JInternalFrame {
    
    private static final DecimalFormat df = new DecimalFormat("0.00");
    List<PedidoDetalleDTO> detalle;
    public RegistroPedido() {
        initComponents();        
        lblIdCliente.setVisible(false);
        txtCliente.setEditable(false);
        lblIdOrigen.setVisible(false);
        txtOrigen.setEditable(false);
        lblIdDestino.setVisible(false);
        txtDestino.setEditable(false);
        detalle = new ArrayList<PedidoDetalleDTO>();
        
        df.setRoundingMode(RoundingMode.HALF_UP);
        cargarDetalle();
    }
    
    public void cargarDetalle(){        
        DefaultTableModel modelo = (DefaultTableModel) tbLibros.getModel();
        int cantidad = 0;
        double subtotal = 0;
        double impuesto = 0;
        double total = 0;       
        
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn("Cod. Libro");
        modelo.addColumn("Título");
        modelo.addColumn("Autor");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        
        TableColumnModel columnModel=(TableColumnModel)tbLibros.getColumnModel();
        columnModel.getColumn(3).setCellRenderer(renderer);
        columnModel.getColumn(4).setCellRenderer(renderer);
        
        for (PedidoDetalleDTO dt : detalle) {
            Object[] fila = new Object[5];
            fila[0] = dt.getIdLibro();
            fila[1] = dt.getNomLibro();
            fila[2] = dt.getAutorLibro();
            fila[3] = dt.getCantidad();
            fila[4] = dt.getPrecio();
            modelo.addRow(fila);
            cantidad = cantidad + dt.getCantidad();
            impuesto = impuesto + dt.getImpuesto();
            total = total + dt.getTotal();
        }
        subtotal = MultiHelper.round(total - impuesto,2);
        
        lblCantidad.setText(String.valueOf(cantidad));
        lblSubTotal.setText(df.format(subtotal));
        lblImpuesto.setText(df.format(impuesto));
        lblTotal.setText(df.format(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblIdCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarLibro = new javax.swing.JButton();
        btnQuitarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLibros = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlDatosUbicacion = new javax.swing.JPanel();
        pnlParametrosUbicacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBuscarPuntoOrigen = new javax.swing.JButton();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        btnBuscarPuntoDestino = new javax.swing.JButton();
        lblIdOrigen = new javax.swing.JLabel();
        lblIdDestino = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlDatosCompra.setPreferredSize(new java.awt.Dimension(500, 582));

        jLabel1.setText("Cliente");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Libros");

        btnAgregarLibro.setText("Agregar");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnQuitarLibro.setText("Quitar");
        btnQuitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLibroActionPerformed(evt);
            }
        });

        tbLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbLibros);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("NUEVA COMPRA");

        jLabel5.setText("Cantidad");

        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidad.setText("lblCantidad");

        jLabel7.setText("Sub Total");

        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotal.setText("lblSubTotal");

        jLabel6.setText("Impuesto");

        lblImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImpuesto.setText("lblImpuesto");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Total");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("lblTotal");

        javax.swing.GroupLayout pnlDatosCompraLayout = new javax.swing.GroupLayout(pnlDatosCompra);
        pnlDatosCompra.setLayout(pnlDatosCompraLayout);
        pnlDatosCompraLayout.setHorizontalGroup(
            pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(84, 84, 84)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCompraLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)
                        .addComponent(lblImpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCompraLayout.createSequentialGroup()
                        .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosCompraLayout.createSequentialGroup()
                        .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                                .addComponent(txtCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                                .addComponent(btnAgregarLibro)
                                .addGap(12, 12, 12)))
                        .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQuitarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                        .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        pnlDatosCompraLayout.setVerticalGroup(
            pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosCompraLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuitarLibro)
                        .addComponent(btnAgregarLibro)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblImpuesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotal))
                .addGap(70, 70, 70))
        );

        getContentPane().add(pnlDatosCompra);

        pnlParametrosUbicacion.setPreferredSize(new java.awt.Dimension(596, 180));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("DELIVERY");

        jLabel10.setText("Ubicación Origen");

        jLabel11.setText("Ubicación Destino");

        btnBuscarPuntoOrigen.setText("Buscar");
        btnBuscarPuntoOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPuntoOrigenActionPerformed(evt);
            }
        });

        btnBuscarPuntoDestino.setText("Buscar");
        btnBuscarPuntoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPuntoDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlParametrosUbicacionLayout = new javax.swing.GroupLayout(pnlParametrosUbicacion);
        pnlParametrosUbicacion.setLayout(pnlParametrosUbicacionLayout);
        pnlParametrosUbicacionLayout.setHorizontalGroup(
            pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosUbicacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlParametrosUbicacionLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(lblIdOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlParametrosUbicacionLayout.createSequentialGroup()
                        .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlParametrosUbicacionLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(31, 31, 31)
                                .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlParametrosUbicacionLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addComponent(txtOrigen)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarPuntoDestino)
                            .addComponent(btnBuscarPuntoOrigen))
                        .addGap(75, 75, 75))))
        );
        pnlParametrosUbicacionLayout.setVerticalGroup(
            pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosUbicacionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblIdOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnBuscarPuntoOrigen)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParametrosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPuntoDestino))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosUbicacionLayout = new javax.swing.GroupLayout(pnlDatosUbicacion);
        pnlDatosUbicacion.setLayout(pnlDatosUbicacionLayout);
        pnlDatosUbicacionLayout.setHorizontalGroup(
            pnlDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParametrosUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        pnlDatosUbicacionLayout.setVerticalGroup(
            pnlDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosUbicacionLayout.createSequentialGroup()
                .addComponent(pnlParametrosUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(859, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDatosUbicacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        try {
            BusquedaLibro.libroSeleccionado = null;
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            BusquedaLibro obj = new BusquedaLibro(topFrame, true);
            obj.setVisible(true);
            if(BusquedaLibro.libroSeleccionado != null){
                int conta=0;
                for(var x : detalle){
                    if(x.getIdLibro().equalsIgnoreCase(BusquedaLibro.libroSeleccionado.getIdLibro())){
                        conta++;
                        break;
                    }
                }
                if(conta>0){
                    JOptionPane.showMessageDialog(this, "El libro agregado ya se encuentra agregado");
                }else{
                    detalle.add(BusquedaLibro.libroSeleccionado);
                }
                
            }
            cargarDetalle();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error interno del sistema");
        }
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnQuitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLibroActionPerformed
        try {
            int fila = tbLibros.getSelectedRow();

            if (fila != -1) {
                String idLibro = tbLibros.getValueAt(fila, 0).toString();
                if(!detalle.removeIf(x->x.getIdLibro().equalsIgnoreCase(idLibro))){
                    JOptionPane.showMessageDialog(this, "Error interno del sistema");
                }
                cargarDetalle();
            } else {
                JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna fila");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error interno del sistema");
        }
    }//GEN-LAST:event_btnQuitarLibroActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        try {
            BusquedaCliente.clienteSeleccionado = null;
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            BusquedaCliente obj = new BusquedaCliente(topFrame, true);
            obj.setVisible(true);
            if(BusquedaCliente.clienteSeleccionado != null){
                lblIdCliente.setText(BusquedaCliente.clienteSeleccionado.getId());
                txtCliente.setText(BusquedaCliente.clienteSeleccionado.getNombreCompleto());
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error interno del sistema");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarPuntoOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPuntoOrigenActionPerformed
        try {
            BusquedaPunto.puntoSeleccionado = null;
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            BusquedaPunto obj = new BusquedaPunto(topFrame, true);
            obj.setVisible(true);
            if(BusquedaPunto.puntoSeleccionado != null){
                lblIdOrigen.setText(BusquedaPunto.puntoSeleccionado.getId());
                txtOrigen.setText(BusquedaPunto.puntoSeleccionado.getNombreUbicacion());
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error interno del sistema");
        }
    }//GEN-LAST:event_btnBuscarPuntoOrigenActionPerformed

    private void btnBuscarPuntoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPuntoDestinoActionPerformed
        try {
            BusquedaPunto.puntoSeleccionado = null;
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            BusquedaPunto obj = new BusquedaPunto(topFrame, true);
            obj.setVisible(true);
            if(BusquedaPunto.puntoSeleccionado != null){
                lblIdDestino.setText(BusquedaPunto.puntoSeleccionado.getId());
                txtDestino.setText(BusquedaPunto.puntoSeleccionado.getNombreUbicacion());
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error interno del sistema");
        }
    }//GEN-LAST:event_btnBuscarPuntoDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarPuntoDestino;
    private javax.swing.JButton btnBuscarPuntoOrigen;
    private javax.swing.JButton btnQuitarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdDestino;
    private javax.swing.JLabel lblIdOrigen;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDatosCompra;
    private javax.swing.JPanel pnlDatosUbicacion;
    private javax.swing.JPanel pnlParametrosUbicacion;
    private javax.swing.JTable tbLibros;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
